# Generated by Django 5.2.6 on 2025-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mechanicprofile_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='approved',
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='service_center_name',
            field=models.CharField(max_length=100),
        ),
    ]
