# Generated by Django 4.2 on 2025-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='owner_name',
            field=models.CharField(default='Testuser', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_brand',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_model',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_number',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_year',
            field=models.PositiveIntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default='2025'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('towing', 'Towing'), ('fuel', 'Fuel Delivery'), ('battery', 'Battery Jumpstart'), ('tire', 'Tire Replacement'), ('other', 'Other')], max_length=20),
        ),
    ]
