# Generated by Django 5.2.6 on 2025-10-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_mechanicprofile_location'),
        ('services', '0005_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='accounts.mechanicprofile'),
        ),
    ]
