# Generated by Django 5.2.6 on 2025-10-21 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_mechanicprofile_approved'),
        ('services', '0007_alter_feedback_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'mechanic')},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='estimated_completion_time',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServiceAssignment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='service_request',
        ),
    ]
