# Generated by Django 5.2.6 on 2025-10-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mechanicprofile_is_available_and_more'),
        ('services', '0008_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='accounts.mechanicprofile'),
        ),
    ]
