# Generated by Django 4.2 on 2025-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='service_center_name',
            field=models.CharField(max_length=100),
        ),
    ]
