# Generated by Django 4.2 on 2025-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_mechanicprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='address',
            field=models.TextField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='service_center_name',
            field=models.CharField(max_length=255),
        ),
    ]
