# Generated by Django 4.2 on 2025-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mechanicprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
