# Generated by Django 4.2 on 2025-10-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_mechanicprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
