# Generated by Django 4.2 on 2025-10-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mechanicprofile_approved_mechanicprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='location',
            field=models.TextField(default='Unknown Location'),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='service_center_name',
            field=models.CharField(max_length=255),
        ),
    ]
