# Generated by Django 5.2.6 on 2025-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mechanicprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
