# Generated by Django 5.2.6 on 2025-10-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_mechanicprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
