# Generated by Django 5.2.6 on 2025-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_mechanicprofile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
