# Generated by Django 4.2 on 2025-10-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mechanicprofile_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='is_available',
        ),
    ]
