# Generated by Django 4.2 on 2025-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_mechanicprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
