# Generated by Django 4.2 on 2025-10-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_mechanicprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
