# Generated by Django 4.2 on 2025-10-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mechanicprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
