# Generated by Django 5.2.6 on 2025-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_mechanicprofile_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
